### ISSUE TITLE
Bad example command in docker/README.md 

### ISSUE THREAD

**Issue by leviable** [notsatan/go-template#23]
The `README.md` file generated in the `docker/` directory specifies a command that is incompatible with the generated Dockerfile. Specifically:

![image](https://user-images.githubusercontent.com/11619428/148065022-ba90fa44-c033-4838-adf3-dacc49c7c4e3.png)

Since the final image created by the Dockerfile is a `scratch` image, there is no shell to attach to:

```
$ docker run -it --rm -v $(pwd):/workspace go-template-test bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "bash": executable file not found in $PATH: unknown.
```

The suggested command should probably be something like this:
```
$ docker run --rm go-template-test
Running project: go-template-test
```
It might also be worthwhile to add support to the Makefile for generating a "production" image that is based on `scratch`, and a "development" or "debug" image that is based on an `alpine` or `bash` image. For instance:
 `make docker-gen DEBUG=true`

**Comment by notsatan** [comment]
Thanks for pointing this out - probably something that I missed out on while polishing the documentation. Will raise a PR to fix this in some time!

> It might also be worthwhile to add support to the Makefile for generating a "production" image that is based on scratch, and a "development" or "debug" image

That sounds like a good idea - but should be a separate issue by itself for record-keeping.

A naive solution I can think of is to create another dockerfile that would be run for the debug builds (this one won't have multi-stage builds) - is there a better way to implement this? 

> For instance: `make docker-gen DEBUG=true`

For the command, creating a new Makefile command instead of adding a variable sounds better, something like `make docker-debug` (open to suggestions). Since most shells support tab-completion with Makefile commands, just three taps would be enough to get the command, with no chances of typos!

**Comment by leviable** [comment]
Agreed on `docker-debug` over an ENV variable.

> A naive solution I can think of is to create another dockerfile that would be run for the debug builds (this one won't have multi-stage builds) - is there a better way to implement this?

I'd use one Dockerfile and leverage build args, something like:

Makefile:
```Makefile
.PHONY: docker-gen
## `docker-gen`: Create a new docker image for the project
docker-gen:
	echo "Building docker image \`$(IMAGE):$(VERSION)\`..."
	docker build --rm \
		--build-arg final_image=scratch \
		-t $(IMAGE):$(VERSION) . \
		-f ./docker/Dockerfile
		
.PHONY: docker-debug
## `docker-debug`: Create a new debug docker image for the project
docker-debug:
	echo "Building docker image \`$(IMAGE):$(VERSION)\`..."
	docker build --rm \
		--build-arg final_image=alpine:latest \
		-t $(IMAGE):$(VERSION) . \
		-f ./docker/Dockerfile
		
```

Dockerfile:
```Dockerfile
...
ARG final_image
FROM ${final_image}
...
```
